language: python
python: 2.7
git:
  depth: 3
sudo: false


env:
  global:
    - PIP_INSTALL=pip install
  matrix:
    - TRAVIS_4681_WORKAROUND=1

matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py3 PIP_INSTALL="pip install --user"
    - os: osx
      language: generic
      env: TOXENV=py27 PIP_INSTALL="pip install --user"
    - os: linux
      env: TOXENV=py27
    - os: linux
      env: TOXENV=py32
    - os: linux
      env: TOXENV=py33
    - os: linux
      env: TOXENV=py34
    - os: linux
      env: TOXENV=pypy
    - os: linux
      env: TOXENV=pypy3
    - os: linux
      env: TOXENV=docs
  exclude:
    - env: TRAVIS_4681_WORKAROUND=1
      
before_install:
  - chmod ugo+x .travis_before_install.sh 
  - ./.travis_before_install.sh
#  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then PATH=/usr/local/bin:$PATH; fi;
  
install:
  - echo $PATH
  - which pip
  - which python
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then travis_retry python -m pip install --user "virtualenv<14.0.0" tox; fi
  - if [[ $TRAVIS_OS_NAME != 'osx' ]]; then travis_retry python -m pip install "virtualenv<14.0.0" tox; fi

script: 
  #- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python setup.py build_clib; fi
  - python -m tox
 