language: python
python: 2.7
git:
  depth: 3
sudo: false


env:
  matrix:
    - TRAVIS_4681_WORKAROUND=1


matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py3
    - os: osx
      language: generic
      env: TOXENV=py27
    - os: linux
      env: TOXENV=py27
    - os: linux
      env: TOXENV=py32
    - os: linux
      env: TOXENV=py33
    - os: linux
      env: TOXENV=py34
    - os: linux
      env: TOXENV=pypy
    - os: linux
      env: TOXENV=pypy3
    - os: linux
      env: TOXENV=docs
  exclude:
    - env: TRAVIS_4681_WORKAROUND=1
      
    

#
#env:
#  - TOXENV=py34
#  - TOXENV=py33
#  - TOXENV=py32
#  - TOXENV=pypy3
#  - TOXENV=py27
#  - TOXENV=py26
#  - TOXENV=pypy
#  - TOXENV=docs

before_install:
  - chmod ugo+x .travis_before_install.sh 
  - ./.travis_before_install.sh
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then PATH=/usr/local/bin:$PATH; fi;
  
install:
  - echo $PATH
  - which pip
  - which python
  - travis_retry pip install "virtualenv<14.0.0" tox

script: 
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python setup.py build_chipmunk; fi
  - tox
 