environment:
  matrix:
    - PYTHON: "C:\\Python27"
    #- PYTHON: "C:\\Python27-x64"
    #- PYTHON: "C:\\Python33"
    #- PYTHON: "C:\\Python33-x64"
    #  DISTUTILS_USE_SDK: "1"
    #- PYTHON: "C:\\Python34"
    #- PYTHON: "C:\\Python34-x64"
    #  DISTUTILS_USE_SDK: "1"
    #- PYTHON: "C:\\Python35"
    #- PYTHON: "C:\\Python35-x64"

#platform:
#  - x86
  #- x64

#matrix:
#  fast_finish: true

clone_depth: 3

init:
  - ECHO %PYTHON%

install:
  # tox for testing
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -m pip install tox"
  # We need wheel installed to build wheels
  - "python -m pip install --upgrade wheel"
  # We need mingwpy for compiling
  - "python -m pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy "
  - "python -m pip freeze"
  
build: off
  
test_script:
  - "tox -e py"
  
after_test:
  - "python setup.py bdist_wheel"

artifacts:
  - path: dist\*
